# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
#      - id: double-quote-string-fixer

#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: 'v4.3.21'
#    hooks:
#      - id: isort

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
