
name: continuous_integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2

      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: setting up ssh keys
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: install required packages (python ${{ matrix.python-version }})
        run: |
          ssh-add -l
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: run unit tests (python ${{ matrix.python-version }}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=chimera --cov-append --cov-fail-under=50 --cov-report=xml tests/

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
